INSERT INTO categories (name) VALUES ('Fantasy');
INSERT INTO categories (name) VALUES ('Thriller');
INSERT INTO categories (name) VALUES ('Fiction');
INSERT INTO categories (name) VALUES ('Mystery');
INSERT INTO categories (name) VALUES ('Science');
INSERT INTO categories (name) VALUES ('Romance');
INSERT INTO categories (name) VALUES ('Historical');
INSERT INTO categories (name) VALUES ('Crime');
INSERT INTO authors (first_name,last_name) VALUES ('Roger', 'Porter');
INSERT INTO authors (first_name,last_name) VALUES ('Jeffrey', 'Snyder');
INSERT INTO authors (first_name,last_name) VALUES ('Louis', 'Coleman');
INSERT INTO authors (first_name,last_name) VALUES ('George', 'Powell');
INSERT INTO authors (first_name,last_name) VALUES ('Jane', 'Ortiz');
INSERT INTO authors (first_name,last_name) VALUES ('Randy', 'Morales');
INSERT INTO authors (first_name,last_name) VALUES ('Lisa', 'Davis');
INSERT INTO authors (first_name,last_name) VALUES ('Brenda', 'Griffin');
INSERT INTO authors (first_name,last_name) VALUES ('Steven', 'Murray');
INSERT INTO authors (first_name,last_name) VALUES ('Christina', 'Jordan');
INSERT INTO authors (first_name,last_name) VALUES ('Paul', 'Scott');
INSERT INTO authors (first_name,last_name) VALUES ('Stephen', 'Warren');
INSERT INTO authors (first_name,last_name) VALUES ('Earl', 'Bennett');
INSERT INTO authors (first_name,last_name) VALUES ('Rachel', 'Hunter');
INSERT INTO authors (first_name,last_name) VALUES ('Lillian', 'Robertson');
INSERT INTO authors (first_name,last_name) VALUES ('Randy', 'Graham');
INSERT INTO authors (first_name,last_name) VALUES ('Gloria', 'Chavez');
INSERT INTO authors (first_name,last_name) VALUES ('Frances', 'Ross');
INSERT INTO authors (first_name,last_name) VALUES ('Jessica', 'Bailey');
INSERT INTO authors (first_name,last_name) VALUES ('Julie', 'Washington');
INSERT INTO authors (first_name,last_name) VALUES ('Russell', 'Howard');
INSERT INTO authors (first_name,last_name) VALUES ('Chris', 'Graham');
INSERT INTO authors (first_name,last_name) VALUES ('Amanda', 'Rice');
INSERT INTO authors (first_name,last_name) VALUES ('Steven', 'Owens');
INSERT INTO authors (first_name,last_name) VALUES ('Deborah', 'Nichols');
INSERT INTO authors (first_name,last_name) VALUES ('Wanda', 'Morales');
INSERT INTO authors (first_name,last_name) VALUES ('Norma', 'Scott');
INSERT INTO authors (first_name,last_name) VALUES ('Amy', 'Porter');
INSERT INTO authors (first_name,last_name) VALUES ('Beverly', 'Ford');
INSERT INTO authors (first_name,last_name) VALUES ('Susan', 'Castillo');
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1998-01-20', 27274, 15.31, 'ADULT', 'Absalom',1);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1997-05-05', 6713, 45.78, 'MINOR', 'A che punto Ã¨ la notte',27);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1998-09-14', 16159, 35.56, 'MINOR', 'After Many a Summer Dies the Swan',13);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1999-03-13', 29025, 23.71, 'MINOR', 'Ah',12);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1993-03-12', 9998, 5.26, 'ADULT', 'Wilderness!',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2014-10-22', 18832, 5.69, 'ADULT', 'Alien CornÂ (play)',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2003-02-18', 28741, 34.56, 'ADULT', 'The Alien CornÂ (short story)',22);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1991-10-11', 20471, 7.18, 'TEEN', 'All Passion Spent',19);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1996-03-29', 9457, 45.6, 'MINOR', 'All the King''s Men',1);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2000-11-30', 17327, 14.99, 'MINOR', 'Alone on a Wide',13);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1998-04-23', 3226, 24.37, 'TEEN', 'Wide Sea',11);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1996-03-08', 6171, 34.64, 'ADULT', 'An Acceptable Time',30);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2005-09-07', 10049, 38.51, 'TEEN', 'Antic Hay',9);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1996-10-10', 21765, 3.3, 'MINOR', 'An Evil Cradling',10);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2001-01-24', 2408, 24.4, 'MINOR', 'Arms and the Man',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1992-04-25', 2997, 25.81, 'ADULT', 'As I Lay Dying',24);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2006-09-25', 29543, 20.21, 'ADULT', 'A Time to Kill',7);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2011-10-28', 4893, 18.01, 'MINOR', 'Behold the Man',15);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2012-08-23', 8159, 23.83, 'ADULT', 'Beneath the Bleeding',7);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2006-05-17', 24103, 45.45, 'ADULT', 'Beyond the Mexique Bay',12);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2001-03-25', 22304, 16.68, 'TEEN', 'Blithe Spirit',24);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2007-05-04', 28137, 28.97, 'ADULT', 'Blood''s a Rover',22);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1999-03-03', 20946, 9.76, 'MINOR', 'Blue Remembered Earth',7);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2005-07-27', 9177, 37.17, 'ADULT', 'Blue Remembered Hills',9);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2013-10-29', 17688, 19.51, 'MINOR', 'Bonjour Tristesse',22);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2015-05-06', 26819, 5.63, 'TEEN', 'Brandy of the Damned',16);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1987-07-05', 4894, 3.86, 'TEEN', 'Bury My Heart at Wounded Knee',25);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2002-05-05', 211, 30.66, 'MINOR', 'Butter In a Lordly Dish',25);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2010-10-28', 28396, 14.15, 'MINOR', 'By Grand Central Station I Sat Down and Wept',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2002-05-29', 15170, 37.47, 'TEEN', 'Cabbages and Kings',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2010-01-28', 20513, 3.32, 'MINOR', 'Carrion Comfort',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1991-12-03', 16585, 15.78, 'ADULT', 'A Catskill Eagle',23);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1990-07-20', 14166, 23.87, 'MINOR', 'Clouds of Witness',22);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1993-06-18', 29606, 40.23, 'MINOR', 'A Confederacy of Dunces',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1990-11-06', 22390, 46.43, 'ADULT', 'Consider Phlebas',7);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1987-07-21', 19292, 30.89, 'MINOR', 'Consider the Lilies',13);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2000-10-28', 12346, 40.23, 'TEEN', 'Cover Her Face',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2013-04-06', 2500, 32.68, 'TEEN', 'The Cricket on the Hearth',10);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1989-10-10', 21714, 23.41, 'TEEN', 'The Curious Incident of the Dog in the Night-Time',3);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2000-06-06', 16829, 32.45, 'TEEN', 'The Daffodil Sky',2);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2002-09-08', 2036, 46.52, 'MINOR', 'Dance Dance Dance',23);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1995-04-03', 25151, 36.61, 'ADULT', 'A Darkling Plain',23);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1989-02-26', 3810, 38.64, 'TEEN', 'Death Be Not Proud',5);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2013-12-20', 23115, 2.26, 'TEEN', 'The Doors of Perception',29);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2004-04-04', 18437, 24.86, 'ADULT', 'Down to a Sunless Sea',28);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2007-10-09', 2869, 11.84, 'MINOR', 'Dulce et Decorum Est',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1990-08-15', 24100, 18.58, 'ADULT', 'Dying of the Light',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1988-05-17', 9569, 45.43, 'ADULT', 'East of Eden',20);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2010-09-18', 18857, 22.55, 'ADULT', 'Ego Dominus Tuus',3);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2009-04-15', 24907, 33.96, 'TEEN', 'Endless Night',16);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1994-01-27', 378, 42.35, 'MINOR', 'Everything is Illuminated',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1991-09-08', 681, 1.82, 'TEEN', 'Eyeless in Gaza',27);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2013-01-27', 29100, 43.23, 'MINOR', 'Fair Stood the Wind for France',20);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2002-03-05', 20952, 6.07, 'MINOR', 'Fame Is the Spur',11);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1989-12-06', 24985, 9.41, 'ADULT', 'A Fanatic Heart',23);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1998-09-19', 19285, 8.04, 'TEEN', 'The Far-Distant Oxus',7);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1997-01-10', 6733, 6.05, 'MINOR', 'A Farewell to Arms',17);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1990-10-19', 205, 19.52, 'MINOR', 'Far From the Madding Crowd',28);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2013-04-22', 2790, 44.09, 'MINOR', 'Fear and Trembling',24);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1993-04-19', 5936, 44.68, 'MINOR', 'For a Breath I Tarry',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2010-11-12', 5650, 8.13, 'MINOR', 'For Whom the Bell Tolls',10);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2000-10-03', 22009, 18.24, 'TEEN', 'Frequent Hearses',3);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2004-02-20', 13402, 17.21, 'ADULT', 'From Here to Eternity',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2004-05-24', 20887, 35.59, 'ADULT', 'A Glass of Blessings',27);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2011-08-14', 6127, 43.19, 'TEEN', 'The Glory and the Dream',1);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1993-04-12', 3364, 42.82, 'ADULT', 'The Golden Apples of the Sun',27);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2004-11-13', 661, 38.52, 'MINOR', 'The Golden Bowl',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1994-05-09', 2653, 26.76, 'MINOR', 'Gone with the Wind',13);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1992-06-01', 19998, 22.43, 'ADULT', 'The Grapes of Wrath',20);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2014-10-05', 9344, 1.06, 'TEEN', 'Great Work of Time',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1998-10-21', 17086, 40.07, 'ADULT', 'The Green Bay Tree',16);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1999-10-24', 22125, 48.63, 'MINOR', 'A Handful of Dust',27);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2006-05-15', 15875, 30.37, 'MINOR', 'Have His Carcase',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1992-08-20', 13624, 2.46, 'MINOR', 'The Heart Is a Lonely Hunter',23);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2003-10-16', 19549, 44.8, 'MINOR', 'The Heart Is Deceitful Above All Things',11);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1990-03-18', 1049, 33.85, 'ADULT', 'His Dark Materials',10);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2010-11-18', 288, 46.63, 'TEEN', 'The House of Mirth',29);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1997-01-07', 17285, 29.47, 'MINOR', 'How Sleep the Brave',27);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2014-08-16', 16010, 34.94, 'TEEN', 'How Sleep the Brave',29);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2001-12-05', 13298, 35.6, 'ADULT', 'How Sleep the Brave',23);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1992-09-14', 29432, 23.39, 'TEEN', 'I Know Why the Caged Bird Sings',21);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2014-01-23', 20250, 38.74, 'MINOR', 'I Sing the Body Electric',16);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2004-11-11', 9777, 32.36, 'MINOR', 'I Will Fear No Evil',25);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1992-02-13', 10081, 33.21, 'MINOR', 'If I Forget Thee Jerusalem',7);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2004-03-09', 25437, 6.4, 'ADULT', 'If Not Now',27);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1993-02-25', 24935, 9.14, 'TEEN', 'When?',1);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1987-09-21', 9015, 11.69, 'TEEN', 'Infinite Jest',2);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2006-11-16', 25080, 38.6, 'ADULT', 'In a Dry Season',21);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2006-05-12', 22035, 4.61, 'MINOR', 'In a Glass Darkly',21);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2000-03-14', 29880, 7.19, 'TEEN', 'In Death Ground',1);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2008-06-16', 5401, 41.08, 'TEEN', 'In Dubious Battle',26);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2005-02-19', 13057, 43.75, 'TEEN', 'An Instant In The Wind',26);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1995-07-16', 14714, 8.59, 'TEEN', 'It''s a Battlefield',25);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2001-09-25', 26989, 19.23, 'MINOR', 'Jacob Have I Loved',26);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2002-11-28', 28166, 42.48, 'TEEN', 'O Jerusalem!',7);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2011-12-28', 24465, 16.25, 'ADULT', 'Jesting Pilate',1);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1997-01-18', 10901, 1.45, 'TEEN', 'The Last Enemy',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2012-03-16', 27604, 46.56, 'MINOR', 'The Last Temptation',25);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2005-04-13', 22077, 28.71, 'MINOR', 'The Lathe of Heaven',16);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2005-08-07', 2995, 10.66, 'ADULT', 'Let Us Now Praise Famous Men',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1997-12-13', 1049, 30.75, 'ADULT', 'Lilies of the Field',24);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2006-04-20', 12205, 12.63, 'ADULT', 'This Lime Tree Bower',3);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2001-01-22', 16255, 10.83, 'ADULT', 'The Line of Beauty',29);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1988-06-27', 12696, 24.00 ,'MINOR', 'The Little Foxes',17);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2003-02-05', 27401, 18.74, 'ADULT', 'Little Hands Clapping',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2014-06-22', 4721, 14.95, 'TEEN', 'Look Homeward',9);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2004-10-11', 13319, 48.35, 'ADULT', 'Angel',7);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2011-12-19', 21958, 45.42, 'TEEN', 'Look to Windward',10);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1995-05-09', 2743, 42.18, 'MINOR', 'The Man Within',10);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2007-10-12', 5930, 17.49, 'ADULT', 'Many Waters',15);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2012-07-09', 16591, 47.55, 'ADULT', 'A Many-Splendoured Thing',28);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2004-06-27', 3582, 39.11, 'ADULT', 'The Mermaids Singing',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1997-06-22', 15896, 2.08, 'MINOR', 'The Millstone',29);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2006-03-15', 2046, 38.05, 'MINOR', 'The Mirror Crack''d from Side to Side',15);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2008-06-18', 28201, 1.82, 'MINOR', 'Moab Is My Washpot',24);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1992-01-24', 26490, 46.93, 'ADULT', 'The Monkey''s Raincoat',4);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2013-09-04', 29602, 13.33, 'MINOR', 'A Monstrous Regiment of Women',13);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2013-01-09', 21111, 10.32, 'MINOR', 'The Moon by Night',9);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2006-06-11', 11453, 32.31, 'MINOR', 'Mother Night',10);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1992-11-16', 9110, 28.35, 'ADULT', 'The Moving Finger',5);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2012-06-06', 13052, 12.49, 'MINOR', 'The Moving Toyshop',25);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1991-03-12', 8154, 29.99, 'ADULT', 'Mr Standfast',6);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1998-12-26', 20816, 19.5, 'MINOR', 'Nectar in a Sieve',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2000-10-09', 19045, 14.49, 'TEEN', 'The Needle''s Eye',10);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1998-03-29', 23212, 34.58, 'ADULT', 'Nine Coaches Waiting',9);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2010-02-06', 11131, 24.05, 'MINOR', 'No Country for Old Men',4);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2013-03-06', 20978, 6.44, 'MINOR', 'No Highway',29);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2007-02-25', 22512, 22.98, 'ADULT', 'Noli Me Tangere',4);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2011-02-16', 18641, 6.23, 'MINOR', 'No Longer at Ease',10);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2004-11-17', 28498, 41.4, 'ADULT', 'Now Sleeps the Crimson Petal',16);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2009-04-05', 324, 23.06, 'TEEN', 'Number the Stars',1);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2013-06-22', 12188, 14.83, 'MINOR', 'Of Human Bondage',30);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1992-09-26', 22489, 2.19, 'ADULT', 'Of Mice and Men',3);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1992-02-09', 29592, 46.67, 'TEEN', 'Oh! To be in England',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1989-10-06', 16373, 46.26, 'ADULT', 'The Other Side of Silence',28);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2003-01-17', 3815, 45.78, 'ADULT', 'The Painted Veil',19);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2012-11-04', 24336, 31.99, 'MINOR', 'Pale Kings and Princes',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2014-08-30', 3934, 12.04, 'TEEN', 'The Parliament of Man',27);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1989-05-30', 9687, 45.67, 'TEEN', 'Paths of Glory',2);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2003-07-23', 20601, 31.15, 'TEEN', 'A Passage to India',25);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1995-03-03', 3416, 49.9, 'TEEN', 'O Pioneers!',26);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1995-08-20', 23030, 48.23, 'ADULT', 'Postern of Fate',9);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2010-01-07', 29854, 45.91, 'MINOR', 'Precious Bane',10);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1992-09-13', 27354, 47.63, 'TEEN', 'The Proper Study',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2003-02-24', 13138, 28.66, 'TEEN', 'Quo Vadis',30);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1989-07-24', 24402, 18.41, 'ADULT', 'Recalled to Life',7);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2010-05-04', 19376, 22.64, 'MINOR', 'Recalled to Life',21);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2008-06-23', 23899, 14.34, 'TEEN', 'Ring of Bright Water',30);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1989-03-15', 5084, 11.27, 'TEEN', 'The Road Less Traveled',17);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2008-05-17', 18967, 20.45, 'TEEN', 'A Scanner Darkly',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2012-06-12', 16930, 34.99, 'TEEN', 'Shall not Perish',26);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1995-10-22', 3476, 45.17, 'MINOR', 'The Skull Beneath the Skin',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1991-12-18', 1556, 22.54, 'ADULT', 'The Soldier''s Art',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1991-01-18', 11042, 4.62, 'ADULT', 'Some Buried Caesar',30);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1993-12-22', 23331, 30.87, 'ADULT', 'Specimen Days',16);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1997-02-27', 13629, 26.81, 'MINOR', 'The Stars'' Tennis Balls',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2006-01-06', 5340, 27.17, 'MINOR', 'Stranger in a Strange Land',4);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1991-11-13', 1832, 9.98, 'MINOR', 'Such',19);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2000-12-03', 12429, 19.27, 'TEEN', 'Such Were the Joys',23);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2000-06-06', 10179, 22.81, 'MINOR', 'A Summer Bird-Cage',16);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1991-06-07', 16301, 20.4, 'MINOR', 'The Sun Also Rises',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2014-12-02', 2138, 1.27, 'MINOR', 'Surprised by Joy',16);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2003-02-09', 1727, 15.55, 'TEEN', 'A Swiftly Tilting Planet',22);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1992-10-18', 13829, 10.06, 'MINOR', 'Taming a Sea Horse',25);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1994-03-13', 11647, 37.34, 'MINOR', 'Tender Is the Night',21);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1992-12-12', 27153, 35.39, 'ADULT', 'Terrible Swift Sword',2);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1991-07-08', 15918, 20.11, 'ADULT', 'That Good Night',5);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1993-09-11', 13597, 48.63, 'TEEN', 'That Hideous Strength',21);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2008-01-26', 22855, 40.02, 'ADULT', 'Things Fall Apart',1);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2013-04-03', 8009, 48.32, 'TEEN', 'This Side of Paradise',25);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1987-05-19', 26931, 33.81, 'MINOR', 'Those Barren Leaves',5);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1991-05-14', 10810, 21.41, 'MINOR', 'Thrones',23);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2009-02-05', 5371, 15.54, 'MINOR', 'Dominations',17);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1988-09-24', 2627, 11.42, 'ADULT', 'Tiger! Tiger!',28);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2003-08-05', 15625, 38.58, 'ADULT', 'A Time of Gifts',1);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2005-08-15', 11601, 23.29, 'TEEN', 'Time of our Darkness',19);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '1999-08-21', 12654, 5.93, 'TEEN', 'Time To Murder And Create',8);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1987-08-26', 26739, 2.21, 'ADULT', 'Tirra Lirra by the River',28);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2004-04-04', 13659, 27.05, 'ADULT', 'To a God Unknown',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1999-08-13', 25080, 34.06, 'ADULT', 'To Sail Beyond the Sunset',13);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1988-02-24', 25541, 8.88, 'TEEN', 'To Say Nothing of the Dog',26);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2004-04-06', 21573, 38.95, 'TEEN', 'To Your Scattered Bodies Go',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2003-02-05', 249, 35.35, 'ADULT', 'The Torment of Others',17);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2003-03-12', 6660, 38.39, 'MINOR', 'Unweaving the Rainbow',13);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1996-10-28', 18708, 47.19, 'TEEN', 'Vanity Fair',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '1996-09-30', 1092, 44.27, 'MINOR', 'Vile Bodies',19);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '1993-10-21', 12978, 34.49, 'MINOR', 'The Violent Bear It Away',19);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2011-09-09', 28211, 38.13, 'TEEN', 'Waiting for the Barbarians',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('GOLD', '2010-07-28', 5146, 10.46, 'ADULT', 'The Waste Land',28);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2004-01-17', 19962, 33.99, 'TEEN', 'The Way of All Flesh',22);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2000-08-10', 23466, 42.61, 'MINOR', 'The Way Through the Woods',15);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2013-10-15', 29051, 48.48, 'ADULT', 'The Wealth of Nations',18);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('PROMO', '2001-09-16', 5422, 41.00, 'TEEN' ,'What''s Become of Waring',1);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2002-11-29', 17903, 32.42, 'ADULT', 'When the Green Woods Laugh',14);
INSERT INTO books (edition_type,release_date,copies,price,age_restriction,title,author_id) VALUES ('NORMAL', '2005-05-21', 24849, 24.76, 'ADULT', 'Where Angels Fear to Tread',26);
INSERT INTO books_categories (book_id, category_id) VALUES (1, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (1, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (2, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (2, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (2, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (2, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (3, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (3, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (3, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (4, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (4, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (4, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (4, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (4, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (5, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (5, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (5, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (5, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (6, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (6, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (6, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (6, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (7, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (7, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (7, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (7, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (7, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (8, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (9, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (9, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (10, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (10, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (10, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (11, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (11, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (11, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (11, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (11, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (12, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (12, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (13, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (13, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (14, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (14, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (14, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (14, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (14, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (15, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (15, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (15, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (15, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (15, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (16, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (16, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (16, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (17, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (17, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (17, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (17, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (17, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (17, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (18, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (18, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (18, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (18, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (19, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (20, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (20, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (20, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (20, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (20, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (20, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (21, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (21, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (21, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (22, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (22, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (22, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (22, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (23, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (23, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (23, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (23, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (24, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (24, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (24, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (24, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (25, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (25, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (25, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (25, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (25, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (25, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (26, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (26, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (26, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (26, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (27, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (27, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (27, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (27, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (27, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (27, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (28, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (29, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (29, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (29, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (29, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (30, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (30, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (30, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (30, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (30, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (30, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (30, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (31, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (31, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (31, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (31, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (31, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (32, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (33, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (33, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (34, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (34, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (34, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (34, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (35, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (35, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (35, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (35, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (35, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (36, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (36, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (36, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (36, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (36, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (36, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (37, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (37, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (38, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (38, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (39, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (39, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (39, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (40, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (40, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (40, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (40, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (41, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (41, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (41, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (41, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (41, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (42, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (42, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (43, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (44, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (44, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (44, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (45, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (45, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (45, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (45, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (46, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (46, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (46, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (46, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (46, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (47, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (47, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (47, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (47, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (47, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (47, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (48, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (48, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (49, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (49, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (49, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (49, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (49, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (50, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (50, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (51, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (51, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (51, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (51, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (52, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (52, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (52, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (53, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (53, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (53, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (54, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (54, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (54, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (54, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (54, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (55, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (56, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (56, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (56, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (56, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (56, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (57, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (57, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (57, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (58, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (58, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (58, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (58, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (58, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (58, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (59, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (60, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (60, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (60, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (61, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (61, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (62, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (63, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (63, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (63, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (63, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (64, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (64, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (64, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (64, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (65, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (65, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (66, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (66, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (66, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (66, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (66, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (67, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (67, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (67, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (67, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (67, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (68, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (68, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (69, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (69, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (70, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (70, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (70, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (70, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (70, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (71, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (71, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (72, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (72, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (72, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (72, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (72, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (73, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (73, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (73, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (73, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (74, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (74, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (75, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (75, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (75, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (76, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (76, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (76, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (76, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (76, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (77, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (77, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (77, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (77, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (78, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (78, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (78, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (78, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (78, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (79, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (79, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (79, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (79, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (80, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (80, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (80, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (80, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (81, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (82, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (82, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (82, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (82, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (82, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (83, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (83, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (83, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (83, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (83, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (83, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (84, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (84, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (84, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (84, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (84, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (84, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (85, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (85, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (85, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (85, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (86, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (86, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (86, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (86, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (87, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (87, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (87, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (87, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (87, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (88, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (88, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (88, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (89, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (89, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (89, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (90, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (90, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (90, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (90, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (90, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (91, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (91, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (91, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (91, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (91, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (92, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (92, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (92, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (92, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (93, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (93, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (93, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (93, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (93, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (94, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (94, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (95, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (95, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (95, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (96, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (96, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (96, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (96, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (97, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (97, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (98, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (98, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (98, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (99, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (99, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (99, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (99, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (99, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (100, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (100, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (101, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (101, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (101, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (101, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (102, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (103, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (103, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (103, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (104, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (104, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (104, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (104, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (105, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (105, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (106, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (106, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (106, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (107, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (107, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (107, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (107, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (108, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (108, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (108, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (108, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (109, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (110, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (110, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (110, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (111, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (111, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (111, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (111, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (112, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (112, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (113, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (113, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (113, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (114, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (114, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (114, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (114, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (115, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (116, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (116, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (116, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (117, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (117, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (118, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (118, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (118, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (118, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (118, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (118, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (119, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (119, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (119, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (119, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (120, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (120, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (120, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (120, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (121, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (121, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (121, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (122, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (122, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (122, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (122, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (123, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (123, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (123, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (123, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (123, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (123, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (124, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (124, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (124, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (124, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (124, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (125, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (125, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (126, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (126, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (126, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (126, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (126, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (127, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (127, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (127, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (127, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (128, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (128, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (128, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (128, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (128, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (129, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (129, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (129, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (130, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (130, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (130, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (130, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (131, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (131, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (131, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (131, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (132, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (132, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (132, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (132, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (132, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (133, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (133, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (134, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (135, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (135, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (135, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (135, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (136, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (136, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (136, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (136, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (136, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (137, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (137, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (138, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (138, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (138, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (138, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (138, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (139, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (139, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (139, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (140, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (140, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (140, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (141, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (141, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (141, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (141, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (141, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (141, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (142, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (142, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (142, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (142, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (143, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (143, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (143, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (143, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (143, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (144, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (144, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (144, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (144, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (144, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (144, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (145, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (145, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (145, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (145, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (145, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (146, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (146, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (146, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (146, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (147, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (148, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (148, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (148, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (148, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (148, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (149, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (149, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (150, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (150, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (151, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (152, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (153, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (153, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (153, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (153, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (153, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (154, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (154, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (154, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (155, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (155, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (155, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (156, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (156, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (156, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (156, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (157, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (157, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (158, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (158, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (158, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (159, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (159, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (159, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (159, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (159, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (160, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (160, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (160, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (161, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (161, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (161, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (161, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (161, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (162, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (162, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (162, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (162, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (163, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (164, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (164, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (164, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (165, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (165, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (165, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (165, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (166, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (166, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (167, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (167, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (167, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (167, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (167, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (168, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (168, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (168, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (168, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (169, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (169, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (169, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (169, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (170, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (170, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (170, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (170, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (170, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (170, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (171, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (171, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (171, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (171, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (172, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (172, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (172, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (172, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (173, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (173, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (173, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (173, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (174, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (174, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (174, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (175, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (175, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (175, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (175, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (175, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (176, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (176, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (176, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (177, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (177, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (177, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (177, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (178, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (178, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (178, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (179, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (179, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (179, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (180, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (180, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (180, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (180, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (181, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (182, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (182, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (182, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (182, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (183, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (183, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (183, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (184, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (184, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (184, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (184, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (184, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (184, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (185, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (185, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (185, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (186, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (186, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (186, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (187, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (187, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (188, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (188, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (188, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (188, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (189, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (189, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (189, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (189, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (190, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (190, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (190, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (190, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (190, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (191, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (191, 7);
INSERT INTO books_categories (book_id, category_id) VALUES (192, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (192, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (192, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (193, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (193, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (193, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (193, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (193, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (194, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (194, 4);
INSERT INTO books_categories (book_id, category_id) VALUES (194, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (194, 6);
INSERT INTO books_categories (book_id, category_id) VALUES (194, 3);
INSERT INTO books_categories (book_id, category_id) VALUES (195, 2);
INSERT INTO books_categories (book_id, category_id) VALUES (195, 1);
INSERT INTO books_categories (book_id, category_id) VALUES (195, 8);
INSERT INTO books_categories (book_id, category_id) VALUES (195, 5);
INSERT INTO books_categories (book_id, category_id) VALUES (195, 6);